version: '3'

services:
  plexsync:
    image: eben0/plexsync:latest
    environment:
      PLEX_TOKEN: xxxxxxxxx
      RADARR_TOKEN: xxxxxxxxx
      RADARR_HOST: radarr:7878
      SONARR_TOKEN: xxxxxxxxx
      SONARR_HOST: sonarr:8989
    restart: unless-stopped